# Generated by Django 5.0.4 on 2024-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produccion_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='litros_totales',
            field=models.IntegerField(default=0),
        ),
    ]
